[template.environment]
  GQL_HOST = "https://nashast.store/graphql"
  NUXT_IMAGE_DOMAINS = "nashastore.netlify.app"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://nashast.store/.*"]
